### ISSUE TITLE
[pixels-cache] test JNI interface to read data from c libs

### ISSUE THREAD

**Issue by ray6080** [pixelsdb/pixels#12]
JNI is our only choice currently if we want to replace existing cache module with a c lib.
Before doing this, I will test the JNI interface to read data of various size from KBs to MBs from outside of JVM heap.
If JNI has reasonable overhead for this. we can move on further.

**Comment by bianhq** [comment]
JNI is already tested and used in Pixels, e.g., in the cache reader and direct local I/Os. However, rewriting Pixels reader using C++ needs further consideration and might be addressed by another issue.
