### ISSUE TITLE
[pixels-core] encode/decode refactoring

### ISSUE THREAD

**Issue by ray6080** [pixelsdb/pixels#13]
Currently, decoders and encoders are almost the same as those in ORC, however, those codes are not written clearly enough.
Refactoring is needed to make this more maintainable later, and more tests are needed to improve performance further.

Meanwhile, there are several updates in later releases of ORC project maybe related (need further check, I'm not sure yet) shall be followed.

**Comment by bianhq** [comment]
We will open issues to fix each specific problem in data encoding / decoding, especially in a C++ reader.
