### ISSUE TITLE
[pixels-presto, pixels-core] optimize pixels reader

### ISSUE THREAD

**Issue by ray6080** [pixelsdb/pixels#14]
1. try to reduce CPU usage with smarter reading strategies, like avoiding data decoding.
2. Issue #13 is closely related with the reader performance.
3. PR #4 is closely related, too.

**Comment by bianhq** [comment]
> > [Even faster ORC](https://prestosql.io/blog/2019/04/23/even-faster-orc.html)
> > This is a good article on how Presto optimize reading on ORC files.
> > We should refer more on Presto's ORC reader implementation.
> 
> Is this article more related to ColumnReaders in pixels-core? PixelsPageSource is optimized in our previous issues, only Timestamp type has a loop in PixelsPageSource.

Timestamp in PixelsPageSource is also optimized.

**Comment by bianhq** [comment]
Close this issue. Future optimizations on the reader will be addressed in other specific issues.
