### ISSUE TITLE
[pixels-core] date column writer produces the wrong date number

### ISSUE THREAD

**Issue by yuly16** [pixelsdb/pixels#419]
Reproduce the issue:

First, we create a table with a date column, the filename is `test_date.tbl`. The file only contains 6 rows:

![image](https://user-images.githubusercontent.com/41314695/231777269-79353ce4-04bb-498f-9b08-c30573bbbe8c.png)

We call pixels-sink to generate `test_date.pxl` file, and then use trino:

![image](https://user-images.githubusercontent.com/41314695/231777233-b9c94a06-1f0d-4e9c-b2b7-9b63ea519c71.png)

The date in `test_date.pxl` is different from `test_date.tbl`. 

The problematic function is `millisToDay` in `DatetimeUtils.java`. When writing the date to pxl file,  `millisToDay` is responsible for translating `Date` to `int`. The scratch date is `1970-01-01`. However, I notice that this function translates `1970-01-02` to 0, while the correct anwser should be 1.

**Comment by bianhq** [comment]
Fixed.
