### ISSUE TITLE
[pixels-cli] string split issue caused by null value.

### ISSUE THREAD

**Issue by yuly16** [pixelsdb/pixels#512]
In `PixelsConsumer.java`, we use `split` function to split elements in a row. However, when the row has null values and the null values are in the end of row, `valueIdx` would larger than the length of `colsInLine` and cause the out-of-range exception.

For example, a row is `a|b|c||` and the splitter is `|`.  This row has two null values. In this case,`colsInLine` should be `["a", "b", "c", "", ""]`. However, the `split` function ignores the splitter at the end of the string, so the value becomes:
![image](https://github.com/pixelsdb/pixels/assets/41314695/a8e50c8c-4e77-4480-ae17-33553f0a1b01)

By the way, It is correct when the splliter happens at the beginning of the string. For example the row is `||a|b|c`. This row has 2 null values, which are the first and second column of this row. In this case,`colsInLine` is:
![image](https://github.com/pixelsdb/pixels/assets/41314695/4c2b6d39-4b38-4374-8a46-28ddb5b6ae46)

 
Based on the observations above, when the row is `a|b|c||`, The following code is erroneous:
```
        // valueIdx would be 0, 1, 2, 3 and 4
        int valueIdx = orderMapping[i];  
        // when valueIdx = 3 or 4, the out-of-range exception happens because the length of colsInLine is 3
        if (colsInLine[valueIdx].isEmpty() ||  
                colsInLine[valueIdx].equalsIgnoreCase("\\N"))
        {
                    columnVectors[i].addNull();
        } else
        {
            columnVectors[i].add(colsInLine[valueIdx]);
        }
```

The suggested fix is:
```
        int valueIdx = orderMapping[i];
        if (valueIdx >= colsInLine.length ||
                colsInLine[valueIdx].isEmpty() ||
                colsInLine[valueIdx].equalsIgnoreCase("\\N"))
        {
            columnVectors[i].addNull();
        } else
        {
            columnVectors[i].add(colsInLine[valueIdx]);
        }
```

**Comment by bianhq** [comment]
Done.
