### ISSUE TITLE
[c++ reader] make string column reader consistent with pixels java reader

### ISSUE THREAD

**Issue by yuly16** [pixelsdb/pixels#546]
1. c++ reader should throw exception if the pixels data is written by big endian
2. Replace length with starts in c++ reader
3. read the info in proto instead of reading pixels.properties #522

**Comment by bianhq** [comment]
4. support dictionary encoding without cascading run-length encoding.

**Comment by bianhq** [comment]
5. revise the column readers and column vectors for time and timestamp, and revise TypeDescription according to PR #562 .

**Comment by bianhq** [comment]
@yuly16 is this issue resolved?

**Comment by bianhq** [comment]
As discussed with @yuly16, this issue has been addressed in the cpp reader.
