### ISSUE TITLE
[pixels-core, c++ reader] null bitmap is not consistent with duckdb validity mask

### ISSUE THREAD

**Issue by yuly16** [pixelsdb/pixels#548]
We would like to directly pass the reference to pixels null bitmap to duckdb validity mask in order to decrease the memory overhead. However, now here are some differences between pixels null bitmap and duckdb validity mask:
1. pixels null bitmap sets the null value as 1, while duckdb validity mask sets the non-null value as 1.
2. pixels null bitmap is big endianness, while duckdb validity mask is little endianness.
3. pixels null bitmap doesn't have alignment, but the type of duckdb validity mask is `uint64_t *`, which means it is 8-byte aligned, and we need to allocate x (x is multiple of 8) bytes for the validity mask (the length of the mask is not required to be multiple of 8).

Here is an example for pixels null bitmap and duckdb validity mask:

Now we have an int column:
`[1, NULL, 3, NULL, NULL, 6, NULL, 8, `
` 9, NULL, 11, 12, NULL, NULL, NULL, 16, `
`17, NULL]`

Pixels null bitmap is: `0x 01011010 01001110 01xxxxxx` (the start address can be any value)

Duckdb validity mask is `0x 10100101 10001101 xxxxxx01 xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx` (the start address must be multiple of 8)

(`x` means this bit doesn't affect our result, but we need to allocate this place for this bit. For example, the length of the duckdb validity mask should be multiple of 8, so we need to allocate some places for `x`).

**Comment by bianhq** [comment]
We plan to solve the endianness problem on the Java side and do bit-flipping on the C++ side.

**Comment by bianhq** [comment]
The endianness of the bitmaps is supported @yuly16. Alignment is still to be supported.

**Comment by bianhq** [comment]
isNull bitmap alignment is supported @yuly16.

**Comment by bianhq** [comment]
@yuly16 please make sure the c++ implementation is consistent with Java implementation.

**Comment by bianhq** [comment]
As discussed with @yuly16, this issue has been resolved in the cpp reader.
