### ISSUE TITLE
[pixels-core] timestamp is not correct in clickbench dataset

### ISSUE THREAD

**Issue by yuly16** [pixelsdb/pixels#556]
I run the clickbench dataset with encoding disabled. The first line in `clickbench.tsv` is:
![image](https://github.com/pixelsdb/pixels/assets/41314695/f5d273dd-4e32-40ff-97cd-e78769e2b519)

However, the result in pixels java is:
![image](https://github.com/pixelsdb/pixels/assets/41314695/9c4bfd66-5338-44d0-9e57-9c684f3cac25)
![image](https://github.com/pixelsdb/pixels/assets/41314695/282d3995-dd9e-4be5-8361-39880baca4c8)
The two timestamp is not correct.

**Comment by bianhq** [comment]
Done.
