### ISSUE TITLE
[c++ reader] Pixels C++ Reader filter pushdown segmentation fault

### ISSUE THREAD

**Issue by liangyongyu-db** [pixelsdb/pixels#564]
In the current pixels C++ version, we set the batch size as `pixelStride` (the default value is 10000). The row group size is usually much larger than `pixelStride`. In this case, filter pushdown doesn't support data skipping very well. For example, if we skip the first batch, we need to execute extra `pixelStride` times of `decoder->next()` to get the start value of the second batch, because we don't know the starting address of the second batch unless we decode all data in the first batch; what's more, the starting value of the second batch might encode with the last value of the first batch together. 

For now we disable the data skipping. In the future we can support the data skipping by adding a new int array in pxl data, which records the starting address of each batch.

**Comment by bianhq** [comment]
This is not a bug after removing data skipping. We can reopen this issue if we come back in the future.
