### ISSUE TITLE
[pixels-invoker-vhive] support invoking multiple knative service

### ISSUE THREAD

**Issue by huasiy** [pixelsdb/pixels#567]
At present, Pixels only specifies a knative service host in the configuration file, which makes it impossible to dynamically configure the VM configuration of the operator. To solve this problem, we can modify the configuration of the vhive client in the configuration file to a list, with the key of each element in list being `knative.service` and the value including comma separated `hostname`, `port`, and `VM configuration`. VM configuration can be written in the form of `1C,200M`, representing one core with 200M memory. For example, a list can be in the following form.
```
knative.service=pixels.default.192.168.1.240.sslip.io,80,1C,200M
knative.service=pixels2.default.192.168.1.240.sslip.io,80,2C,300M 
```

**Comment by bianhq** [comment]
We are not using Knative.
