### ISSUE TITLE
[pixels-core] support vector data type with CRUD operations and top-K similar vector search

### ISSUE THREAD

**Issue by TiannanSha** [pixelsdb/pixels#580]
**Overview**
We aim to introduce a new data type `vector` into pixels for users to store and retrieve vectors (aka embeddings in the context of deep learning). The most performance-critical operation is the Top-K search operation, where user provides a query vector and searches for the Top-K vectors in the database that are most similar to the query vector. To achieve high performance for this Top-K operation, how to do indexing is critical.

**Acceptance criteria**
- introduce a vector data type similar to the binary datatype. A potential issue is the vector might have relatively high dimension.
- use trino udfs to perform all the CRUD and topk search operations (?).

**Comment by bianhq** [comment]
Done.
