### ISSUE TITLE
[c++ reader] resultRowBatch deletion bug

### ISSUE THREAD

**Issue by yuly16** [pixelsdb/pixels#610]
The erroneous query:
```
SELECT SearchPhrase from hits WHERE SearchPhrase <> '' limit 10;
```
When processing the first pxl file, we can acquire enough result, thus we don't need to invoke `readBatch` for the remaining pxl files. However, we allocate memory for `resultRowBatch` in the function `readBatch` and delete the memory in the destructor of `PixelsRecordReaderImpl`. If `readBatch` is not invoked, we still delete `resultRowBatch` in the destructor, which is a nullptr.

**Comment by bianhq** [comment]
Done.
