### ISSUE TITLE
how to connect S3 in trino

### ISSUE THREAD

**Issue by Manuel-Neuer1** [pixelsdb/pixels#637]
作者您好。我现在在测试tpch时使用如下命令：
cd ~/opt/trino-server
./bin/trino --server localhost:8080 --catalog pixels --schema tpch
当我在ec2实例里进入trino后我输入Q1(LINEITEM)的相关sql：
select
l_returnflag,
l_linestatus,
sum(l_quantity) as sum_qty,
sum(l_extendedprice) as sum_base_price,
sum(l_extendedprice*(1-l_discount)) as sum_disc_price,
sum(l_extendedprice*(1-l_discount)(1+l_tax)) as sum_charge,
avg(l_quantity) as avg_qty,
avg(l_extendedprice) as avg_price,
avg(l_discount) as avg_disc,
count() as count_order
from lineitem
where l_shipdate <= date'1998-12-01' - interval '90' day
group by l_returnflag, l_linestatus
order by l_returnflag, l_linestatus;
但是为什么输入后会产生
Query 20240325_221405_00002_wam54 failed: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profiles=[])), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., WebIdentityTokenCredentialsProvider(): Either the environment variable AWS_WEB_IDENTITY_TOKEN_FILE or the javaproperty aws.webIdentityTokenFile must be set., ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profiles=[])): Profile file contained no credentials for profile 'default': ProfileFile(profiles=[]), ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set., InstanceProfileCredentialsProvider(): Failed to load credentials from IMDS.]

我已经在bashrs文件里导入了s3，以及配置了aws configure

难道是在~/opt/trino-server/etc/catalog里配置一个s3.properties吗，但是我配置了一个s3.properties：
connector.name=s3
hive.s3.aws-access-key=...
hive.s3.aws-secret-key=...
hive.s3.endpoint=https://pixels-tpch-1.s3.ap-northeast-1.amazonaws.com
再次执行./bin/trino --server localhost:8080 --catalog pixels --schema tpch进入trino后却报错
请问作者能给出解决方案吗

**Comment by bianhq** [comment]
你好，不需要再trino里面配置s3。只要通过环境变量或者配置文件配置了aws credential就可以。Trino在初次调用Pixels访问S3的时候，Pixels里的S3 Storage会调用AWS SDK来创建S3 client，代码在[这里](https://github.com/pixelsdb/pixels/blob/b9dc5ccafb0a4b235e2f6405e0717f9bb329ca4b/pixels-storage/pixels-storage-s3/src/main/java/io/pixelsdb/pixels/storage/s3/S3.java#L94)。AWS SDK会自动获取环境变量或者AWS配置文件中的credential配置。

你检查一下aws configure是否配置正确。

**Comment by bianhq** [comment]
> 作者您好。我现在在测试tpch时使用如下命令： cd ~/opt/trino-server ./bin/trino --server localhost:8080 --catalog pixels --schema tpch 当我在ec2实例里进入trino后我输入Q1(LINEITEM)的相关sql： select l_returnflag, l_linestatus, sum(l_quantity) as sum_qty, sum(l_extendedprice) as sum_base_price, sum(l_extendedprice*(1-l_discount)) as sum_disc_price, sum(l_extendedprice*(1-l_discount)(1+l_tax)) as sum_charge, avg(l_quantity) as avg_qty, avg(l_extendedprice) as avg_price, avg(l_discount) as avg_disc, count() as count_order from lineitem where l_shipdate <= date'1998-12-01' - interval '90' day group by l_returnflag, l_linestatus order by l_returnflag, l_linestatus; 但是为什么输入后会产生 Query 20240325_221405_00002_wam54 failed: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profiles=[])), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., WebIdentityTokenCredentialsProvider(): Either the environment variable AWS_WEB_IDENTITY_TOKEN_FILE or the javaproperty aws.webIdentityTokenFile must be set., ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profiles=[])): Profile file contained no credentials for profile 'default': ProfileFile(profiles=[]), ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set., InstanceProfileCredentialsProvider(): Failed to load credentials from IMDS.]
> 
> 我已经在bashrs文件里导入了s3，以及配置了aws configure
> 
> 难道是在~/opt/trino-server/etc/catalog里配置一个s3.properties吗，但是我配置了一个s3.properties： connector.name=s3 hive.s3.aws-access-key=... hive.s3.aws-secret-key=... hive.s3.endpoint=https://pixels-tpch-1.s3.ap-northeast-1.amazonaws.com 再次执行./bin/trino --server localhost:8080 --catalog pixels --schema tpch进入trino后却报错 请问作者能给出解决方案吗

您好，这个问题解决了吗？

**Comment by bianhq** [comment]
如果需要可以reopen这个issue.
