### ISSUE TITLE
[pixels-scaling] fix some scaling bugs and upgrade basic policy

### ISSUE THREAD

**Issue by kkzzjx** [pixelsdb/pixels#751]
1. fix error path: move file `io.pixelsdb.pixels.common.turbo.MetricsCollectorProvider` from `META-INF` to `META-INF/services` 
2. fix pom.xml:  add pixels-scaling-general module to pixels root pom
3. add policy helper: add FixSized queue
4. implement basic policy according to pixels-turbo paper

**Comment by bianhq** [comment]
Please add a description @kkzzjx .
